global using System.Collections.Immutable;
global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.Text;
global using Microsoft.CodeAnalysis;
global using Microsoft.CodeAnalysis.CSharp;
global using Microsoft.CodeAnalysis.CSharp.Syntax;
global using ResXLocalize.Avalonia.Extensions;
global using ResXLocalize.Avalonia.StringBuilders;
global using static ResXLocalize.Avalonia.BuildInfo;
global using static ResXLocalize.Avalonia.SourceGenerationTexts;